---
deployment:
  tasks:
    - export DEPLOYPATH=/home/qrestng/public_html/
    - /bin/cp -r /home/qrestng/repositories/qrest/* $DEPLOYPATH
    # - /bin/cp -R * $DEPLOYPATH
    # - /bin/cp -R .htaccess $DEPLOYPATH
    # - /bin/cp -R assets $DEPLOYPATH
    # - /bin/cp -R css $DEPLOYPATH
    # - /bin/cp -R js $DEPLOYPATH
